[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "oblivious-data-store"
version = "0.0.1"
description = "In-memory Path ORAM demo with Flask API"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
include = ["backend*"]
